name: Deploy Widgets to Mainnet
on:
  push:
    branches:
      - main

env:
  ACCOUNT_ID: ${{ vars.MAINNET_ACCOUNT_ID }}
  ACCOUNT_PUBLIC_KEY: ${{ vars.MAINNET_ACCOUNT_PUBLIC_KEY }}
  ACCOUNT_PRIVATE_KEY: ${{ secrets.MAINNET_ACCOUNT_PRIVATE_KEY }}
  NETWORK: mainnet

jobs:
  prepare_environment:
    name: Setup
    uses: ./.github/workflows/setup.yml

  deploy-widgets:
    runs-on: ubuntu-latest
    needs: prepare_environment

    steps:
      - name: Call Setup Workflow
        uses: ./.github/workflows/setup.yml

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy widgets
        run: |
          pnpm run deploy -- "$ACCOUNT_ID" sign-as "$ACCOUNT_ID" network-config "$NETWORK" sign-with-plaintext-private-key --signer-public-key "$ACCOUNT_PUBLIC_KEY" --signer-private-key "$ACCOUNT_PRIVATE_KEY" send