name: Deploy Widgets to Mainnet
on:
  push:
    branches:
      - main

env:
  ACCOUNT_ID: ${{ vars.MAINNET_ACCOUNT_ID }}
  ACCOUNT_PUBLIC_KEY: ${{ vars.MAINNET_ACCOUNT_PUBLIC_KEY }}
  ACCOUNT_PRIVATE_KEY: ${{ secrets.MAINNET_ACCOUNT_PRIVATE_KEY }}
  NETWORK: mainnet

jobs:
  deploy-widgets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy widgets
        run: |
          pnpm run deploy -- "$ACCOUNT_ID" sign-as "$ACCOUNT_ID" network-config "$NETWORK" sign-with-plaintext-private-key --signer-public-key "$ACCOUNT_PUBLIC_KEY" --signer-private-key "$ACCOUNT_PRIVATE_KEY" send