name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sanity_checks:
    name: Sanity Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run code formatting check
        run: pnpm run fmt:check
      - name: Run linting
        run: pnpm run lint