name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  sanity_checks:
    name: Sanity Checks
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yml
      - name: Install dependencies
        run: pnpm install
      - name: Run code formatting check
        run: pnpm run fmt:check
      - name: Run linting
        run: pnpm run lint